version: "3.0"

services:
  backend:
    container_name: backend
    depends_on:
      - database
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://USER:PASSWORD@URL:PORT/DATABASE?schema=public"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
  database:
    image: postgres:latest
    container_name: database
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: code_drops_kanban_todo
    ports:
      - 5432:5432
